CREATE FUNCTION getNthHighestSalary(N IN NUMBER) RETURN NUMBER IS
result NUMBER;
BEGIN
    /* Write your PL/SQL query statement below */
    SELECT SALARY
    INTO result
    -- FROM (SELECT DISTINCT SALARY, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS SLNO FROM EMPLOYEE)
    FROM (SELECT SALARY, ROW_NUMBER() OVER(ORDER BY SALARY DESC) AS SLNO 
        FROM (SELECT DISTINCT SALARY FROM EMPLOYEE))
    WHERE SLNO = N;
    RETURN result;

    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;